datasets:
  logs:
    consumers:
    - criticality: LOW
      name: Dev_Debug_Tool
      owner: Engineering
      type: app
  transactions:
    consumers:
    - criticality: HIGH
      name: CEO_Revenue_Dashboard
      owner: Executive Team
      type: dashboard
    - criticality: MEDIUM
      name: Churn_Prediction_Model
      owner: Data Science
      type: ml_model
